---
title: "Experience"
toc: false
---

### Professional Experience

**Isla Vista Trading Post (IVTP) Co-Outreach Director:** [June 2023 - June 2024]{style="float: right;"}

-   Coordinated and worked 3-for-Free events, in which clothing donations are given away for free to community members to support sustainable fashion at UC Santa Barbara

-   Created 2nd Annual IVTP Zine by managing the project, facilitating brainstorming sessions, keeping club members on track, proofreading and editing, planning launch party, and creating funding request.

-   Helped re-established the IVTP website to increase outreach beyond the local community.

-   Community education via presentation to student groups, such as sorority chapters at UCSB.

-   Implemented organizational changes to club structure including separate weekly executive board meetings, programming calendar, and leadership guides.

**Sustainability Analyst Intern — VOIZ (Voice for Generation Z):** [June 2022 - August 2022]{style="float: right;"}

-   Researched fashion and personal care products to construct 12 sustainability reviews with critical thinking and professional writing.

-   Compiled 3 collections of products and ranked them based on sustainability

-   Awarded “Strongest Reviewer” and “Best Collection”

**Kappa Kappa Gamma Sustainability Chair:** [January – December 2022]{style="float: right;"}

-   Collaborated with a sustainability-focused UCSB club, Gauchos Go Green (formerly Greeks Go Green), to implement strategies to obtain green certification for the chapter house.

-   Educated chapter members on sustainability initiatives, environmental organizations, eco-friendly volunteer opportunities, and personal changes that can improve an individual’s sustainability.

------------------------------------------------------------------------

### Educational Experience

**Colorado State University, Fort Collins, CO** [December 2026]{style="float: right;"}

-   Ecosystem Science and Sustainability P.S.M.

    -   Focus on Water Resources

**University of California, Santa Barbara, CA** [June 2024]{style="float: right;"}

-   Environmental Studies B.A., 3.92 GPA

    -   Concentration in Geography

-   LGBTQ+ Studies Minor

-   Awarded College of Letters and Science Dean’s Honors for 10 quarters

-   Graduated Summa Cum Laude in College of Letters and Sciences

------------------------------------------------------------------------

### Full Resume [View PDF](resumesept2025.pdf){.btn .btn-outline-dark .btn-sm style="float: right;" target="_blank"}

-   updated September 2025



